# Generated by Django 5.2.4 on 2025-08-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='', max_length=30, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
