# Generated by Django 5.2.4 on 2025-08-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_player',
            field=models.BooleanField(default=True, verbose_name='بازیکن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='مربی'),
        ),
    ]
