# Generated by Django 5.2.4 on 2025-08-07 19:00

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_remove_timeslot_court_remove_timeslot_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityrequest',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
