# Generated by Django 5.2.4 on 2025-08-08 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_alter_availabilityrequest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='court',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='courts.court'),
            preserve_default=False,
        ),
    ]
